config.code=2323
config.username=John
config.message=Mensaje de prueba
config.listOfValues=leche,cafe,galletas, Buñuel's
config.valuesMap={product: 'CPU Intel Core I7 14th', description:'Alder Lake, 14 core', price: '1000'}