CREATE DATABASE IF NOT EXISTS Hibernate_Escuela;
USE Hibernate_Escuela;

CREATE TABLE IF NOT EXISTS Cursos (
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(50));

CREATE TABLE IF NOT EXISTS  Estudiantes (
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(50),
curso_id INT,
CONSTRAINT fk_curso FOREIGN KEY (curso_id) REFERENCES Cursos(id) 
    ON DELETE SET NULL ON UPDATE CASCADE 
);

